// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ACPTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ClickOnMicrosoftWord
        /// </summary>
        public void ClickOnMicrosoftWord()
        {
            #region Variable Declarations
            WinClient uIMicrosoftWordDocumenClient = this.UIDocument1MicrosoftWoWindow.UIDocument1Client.UIMicrosoftWordDocumenClient;
            #endregion

            // Click 'Microsoft Word Document' client
            Mouse.Click(uIMicrosoftWordDocumenClient, new Point(733, 254));
        }
        
        /// <summary>
        /// LaunchMicrosoftWord - Use 'LaunchMicrosoftWordParams' to pass parameters into this method.
        /// </summary>
        public void LaunchMicrosoftWord()
        {

            // Launch '%ProgramFiles(x86)%\Microsoft Office\Office14\WINWORD.EXE'
            ApplicationUnderTest wINWORDApplication = ApplicationUnderTest.Launch(this.LaunchMicrosoftWordParams.ExePath, this.LaunchMicrosoftWordParams.AlternateExePath);
        }
        
        #region Properties
        public virtual LaunchMicrosoftWordParams LaunchMicrosoftWordParams
        {
            get
            {
                if ((this.mLaunchMicrosoftWordParams == null))
                {
                    this.mLaunchMicrosoftWordParams = new LaunchMicrosoftWordParams();
                }
                return this.mLaunchMicrosoftWordParams;
            }
        }
        
        public UIDocument1MicrosoftWoWindow UIDocument1MicrosoftWoWindow
        {
            get
            {
                if ((this.mUIDocument1MicrosoftWoWindow == null))
                {
                    this.mUIDocument1MicrosoftWoWindow = new UIDocument1MicrosoftWoWindow();
                }
                return this.mUIDocument1MicrosoftWoWindow;
            }
        }
        #endregion
        
        #region Fields
        private LaunchMicrosoftWordParams mLaunchMicrosoftWordParams;
        
        private UIDocument1MicrosoftWoWindow mUIDocument1MicrosoftWoWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LaunchMicrosoftWord'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class LaunchMicrosoftWordParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Microsoft Office\Office14\WINWORD.EXE'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\Microsoft Office\\Office14\\WINWORD.EXE";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Microsoft Office\Office14\WINWORD.EXE'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles(x86)%\\Microsoft Office\\Office14\\WINWORD.EXE";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDocument1MicrosoftWoWindow : WinWindow
    {
        
        public UIDocument1MicrosoftWoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Document1 - Microsoft Word";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "OpusApp";
            this.WindowTitles.Add("Document1 - Microsoft Word");
            #endregion
        }
        
        #region Properties
        public UIDocument1Client UIDocument1Client
        {
            get
            {
                if ((this.mUIDocument1Client == null))
                {
                    this.mUIDocument1Client = new UIDocument1Client(this);
                }
                return this.mUIDocument1Client;
            }
        }
        #endregion
        
        #region Fields
        private UIDocument1Client mUIDocument1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIDocument1Client : WinClient
    {
        
        public UIDocument1Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Document1";
            this.WindowTitles.Add("Document1 - Microsoft Word");
            #endregion
        }
        
        #region Properties
        public WinClient UIMicrosoftWordDocumenClient
        {
            get
            {
                if ((this.mUIMicrosoftWordDocumenClient == null))
                {
                    this.mUIMicrosoftWordDocumenClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIMicrosoftWordDocumenClient.SearchProperties[WinControl.PropertyNames.Name] = "Microsoft Word Document";
                    this.mUIMicrosoftWordDocumenClient.WindowTitles.Add("Document1 - Microsoft Word");
                    #endregion
                }
                return this.mUIMicrosoftWordDocumenClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIMicrosoftWordDocumenClient;
        #endregion
    }
}
